app99cats/config/routes.rb
App99cats::Application.routes.draw do
  root :to =>'cats#index'
  resources :cats do
    resources :cat_rental_requests, :only => :show
  end
  resources :cat_rental_requests do
    patch 'approve', :on => :member
    patch 'deny', :on => :member
  end
end

app99cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id         :integer          not null, primary key
#  age        :integer
#  birth_date :date
#  color      :string(255)
#  name       :string(255)
#  sex        :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Cat < ActiveRecord::Base
  validates :age, numericality: { only_integer: true }
  validates :name, :age, :color, :sex, :presence => true

  has_many :cat_rental_requests, dependent: :destroy
end

app99cats/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  before_validation :set_default_to_pending
  validates :cat_id, :presence => true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED)}
  validate :overlapping_approved_requests, :on => :create
  belongs_to :cat

  def overlapping_requests
    CatRentalRequest.find_by_sql([<<-SQL, self.cat_id, self.start_date, self.end_date, self.start_date, self.end_date, self.start_date, self.end_date])
    SELECT
      *
    FROM
      cat_rental_requests
    WHERE
      cat_id = ?
    AND
      (? BETWEEN start_date AND end_date)
      OR
      (? BETWEEN start_date AND end_date)
      OR
      (start_date BETWEEN ? AND ?)
      OR
      (end_date BETWEEN ? AND ?)
    SQL
  end

  def overlapping_approved_requests
    overlapping_requests.each do |request|
      if request.status == "APPROVED"
        errors.add(:overlapping_approved_requests, "That cat is already rented out")
      end
    end
  end

  def set_default_to_pending
    self.status ||= "PENDING"
  end

  def deny!
    self.status = "DENIED"
    self.save
  end

  def deny_conflicting_request
    overlapping_requests.each do |request|
      request.deny!
    end
  end

  def approve!
    deny_conflicting_request
    self.status = "APPROVED"
    self.save!
  end

  def self.requests_for_cat_id(cat_id)
    CatRentalRequest.find_by_sql([<<-SQL, cat_id])
    SELECT
      *
    FROM
      cat_rental_requests
    WHERE
      cat_id = ?
    ORDER BY
      start_date, status
    SQL
  end

end

app99cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app99cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @cats = Cat.all
    @rentalrequests = CatRentalRequest.all
    @rentalrequests.
    render :index
  end

  def new
    @catrental = CatRentalRequest.new
    @cats = Cat.all
    render :new
  end

  def create
    @cats = Cat.all
    @catrental = CatRentalRequest.new(cat_rental_params)
    if @catrental.save
      redirect_to cat_rental_request_url(@catrental)
    else
      flash.now[:errors] = @catrental.errors.full_messages
      render :new, :status => 422
    end
  end

  def show
    @catrental = CatRentalRequest.find(params[:id])
    render :show
  end

  def approve
    @request = CatRentalRequest.find(params[:id])
    @request.approve!
    redirect_to cat_rental_requests_url
  end

  def deny
    @request = CatRentalRequest.find(params[:id])
    @request.deny!
    redirect_to cat_rental_requests_url
  end

  private
  def cat_rental_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end

end

app99cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new, :status => 422
    end
  end

  def show
    @cat = Cat.find(params[:id])
    @catrental = CatRentalRequest.requests_for_cat_id(Cat.find(params[:id]))
    render :show
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new, :status => 422
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :age, :sex, :color, :birth_date)
  end
end

app99cats/app/helpers/application_helper.rb
module ApplicationHelper
end

app99cats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app99cats/app/helpers/cats_helper.rb
module CatsHelper
end

app99cats/app/views/cat_rental_requests/index.html.erb
<%= render :partial => "layouts/errors" %>

<table>
  <tr>
    <td><b>Cat</b></td>
    <td><b>Start Date</b></td>
    <td><b>End Date</b></td>
    <td><b>Status</b></td>
    <td><b>Approve</b></td>
    <td><b>Deny</b></td>
  </tr>
  <% @rentalrequests.each do |request|%>
  <tr>
    <td><%= request.cat_id %></td>
    <td><%= request.start_date %></td>
    <td><%= request.end_date %></td>
    <td><%= request.status %></td>
    <td><%= button_to "Approve", approve_cat_rental_request_url(request), :method => :patch %></td>
    <td><%= button_to "Deny", deny_cat_rental_request_url(request), :method => :patch %></td>
    </tr>
  <% end %>
</table>

app99cats/app/views/cat_rental_requests/new.html.erb
<h1>Submit a Cat Request</h1>

<form action="<%= cat_rental_requests_url %>" method="post" accept-charset="utf-8">
  <label for="cat">Cat</label>
  <select name="cat_rental_request[cat_id]" id="cat">
    <option value="">-- Select a cat --</option>
    <% @cats.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select>
  <br>
  <label for="start_date">Start date</label>
  <input type="date" name="cat_rental_request[start_date]" id="start_date" value="<%= @catrental.start_date %>">
  <br>
  <label for="end_date">End date</label>
  <input type="date" name="cat_rental_request[end_date]" id="end_date" value="<%= @catrental.end_date %>">
  <br>

  <p><input type="submit" value="Submit Cat Request"></p>
</form>

app99cats/app/views/cat_rental_requests/show.html.erb
<h1><%= @catrental.cat_id %></h1>

<table>
  <tr>
    <td><b>Start Date</b></td>
    <td><b>End Date</b></td>
  </tr>
  <tr>
    <td><%= @catrental.start_date %></td>
    <td><%= @catrental.end_date%></td>
  </tr>
</table>

<%#= link_to "fix", edit_cat_url %>
<%= link_to "Back to cats", cats_url %>

app99cats/app/views/cats/edit.html.erb
<%= render :partial => "layouts/errors" %>

<h1>Edit Cat</h1>
<%= render :partial => "layouts/form", :locals => {:edit => true}%>

app99cats/app/views/cats/index.html.erb
<%= render :partial => "layouts/errors" %>

<ul>
<% @cats.each do |cat|%>
  <li>
    <%= link_to cat.name, cat_url(cat) %>
  </li>
<% end %>
</ul>

app99cats/app/views/cats/new.html.erb
<h1>Submit a Cat</h1>
<%= render :partial => "layouts/form"%>

app99cats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<h2>Information</h2>

<table>
  <tr>
    <td><b>Age</b></td>
    <td><b>Color</b></td>
    <td><b>Sex</b></td>
  </tr>
  <tr>
    <td><%= @cat.age %></td>
    <td><%= @cat.color%></td>
    <td><%= @cat.sex %></td>
  </tr>
</table>

<h2>Requests</h2>

<table>
  <tr>
    <td><b>Status</b></td>
    <td><b>Start Date</b></td>
    <td><b>End Date</b></td>
  </tr>
  <% @catrental.each do |request| %>
  <tr>
    <td><%= request.status %></td>
    <td><%= request.start_date%></td>
    <td><%= request.end_date %></td>
  </tr>
  <% end %>
</table>

<%= link_to "Edit cat", edit_cat_url %>
<%= link_to "Back to cats", cats_url %>
<%= link_to "Request cat", new_cat_rental_request_url %>

app99cats/app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
  <%= flash[:errors] %>
<% end %>

app99cats/app/views/layouts/_form.html.erb
<% if @cat.persisted? %>
  <form action="<%= cat_url %>" method="post" accept-charset="utf-8">
  <input type="hidden" name="_method" value="PATCH">
<%else%>
  <form action="<%= cats_url %>" method="post" accept-charset="utf-8">
<% end %>
  <label for="cat_name">Cat name</label>
  <input type="text" name="cat[name]" id="cat_name" value="<%= @cat.name %>">
  <br>
  <label for="age">Age</label>
  <input type="text" name="cat[age]" id="age" value="<%= @cat.age %>">
  <br>
  <%if @cat.sex == "M" %>
    <label for="cat_sex_female">Female</label>
    <input type="radio" name="cat[sex]" id="cat_sex_female" value="F">
    <br>
    <label for="cat_sex_male">Male</label>
    <input type="radio" name="cat[sex]" id="cat_sex_male" value="M" checked = "checked">
  <%elsif @cat.sex == "F" %>
    <label for="cat_sex_female">Female</label>
    <input type="radio" name="cat[sex]" id="cat_sex_female" value="F" checked = "checked">
    <br>
    <label for="cat_sex_male">Male</label>
    <input type="radio" name="cat[sex]" id="cat_sex_male" value="M">
  <%else %>
    <label for="cat_sex_female">Female</label>
    <input type="radio" name="cat[sex]" id="cat_sex_female" value="F" >
    <br>
    <label for="cat_sex_male">Male</label>
    <input type="radio" name="cat[sex]" id="cat_sex_male" value="M">
  <%end%>
  <br>
  <label for="cat_coat_color">Coat color</label>
  <select name="cat[color]" id="cat_coat_color">
    <option value="<%= @cat.color %>"><%= @cat.color %></option>
    <option value="Brown">Brown</option>
    <option value="Gold">Gold</option>
    <option value="Black">Black</option>
    <option value="White">White</option>
    <option value="Calico">Calico</option>
  </select>
  <br>
  <label for="birth_date">Birth date</label>
  <input type="date" name="cat[birth_date]" id="birth_date" value="<%= @cat.birth_date %>">
  <br>

  <%#= button_to("Update cat", cat_url(@cat), :method => :patch) %>

  <p><input type="submit" value="Submit Cat"></p>
</form>

app99cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App99cats</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>